name: Check deprecated K8s versions
on: [pull_request]
jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '[".github/workflows/CI*", ".github/workflows/c*", ".github/workflows/det*", ".github/workflows/i*", ".github/workflows/r*", ".github/workflows/s*"]'
  deprecated-version-check:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: deprecated version check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2

      - name: check deprecated versions
        run: |
          ./gh-actions-scripts/install_helm.sh
          ./gh-actions-scripts/install_pluto.sh
          ./gh-actions-scripts/check_deprecated_versions.sh
